### ISSUE TITLE
Issue 1

### ISSUE THREAD

**Issue by Chu127001** [Chu127001/repoTocheckBountyLabel#1]
check bounty added

**Comment by status-open-bounty** [comment]
Current balance: 0.0 ETH
Contract address: [0x920cf6126cac7417c14781436f730c176ecd684c](https://ropsten.etherscan.io/address/0x920cf6126cac7417c14781436f730c176ecd684c)
![QR Code](https://testing.openbounty.status.im/qr/Chu127001/repoTocheckBountyLabel/bounty/1/e45a7cde1b27f9e6434b69ee808d8e3b06bb6cfb1dbae096133f22c61a1ead53/qr.png)
Network: Testnet (Ropsten)
To claim this bounty sign up at [https://testing.openbounty.status.im](https://testing.openbounty.status.im) and make sure to update your Ethereum address in `My Payment Details` so that the bounty is correctly allocated.
To fund it, send test ETH or test ERC20/ERC223 tokens to the contract address.
